app1/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from app1.views import PersonListView, PersonCreateView, PersonUpdateView, PersonDeleteView
from django.conf.urls import url

# from django_filters.views import FilterView
from .models import Person

app_name ="app1"

urlpatterns = [
    path('person_add/', PersonCreateView.as_view(), name='person_add'),
    path('', PersonListView.as_view(), name='person_list'),
    path('person_list/', PersonListView.as_view(), name='person_list'),
    path('<int:pk>/edit/', PersonUpdateView.as_view(), name='person_edit'),
    path('<int:pk>/delete/', PersonDeleteView.as_view(), name='delete'),
    # path('search/', views.search, name='search'),
    # url(r'^search/$', FilterView.as_view(model=Person)),
    url(r'^search/$', views.search, name='search_list' ),
    url(r'^export/$', views.export, name='export'),
    url(r'^simple_upload/$', views.simple_upload, name='simple_upload'),


]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView 

from . import views as myviews
from django.contrib.auth import views


urlpatterns = [
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls),
    path('mysite_2/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path("register/", myviews.register, name="register"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]

app1/models.py
# from django.db import models

# create your models here.
from django.db import models

# create your models here.
from django import forms

from django.utils import timezone

# from concurrency.fields import autoincversionfield


mymultichoices = (
    ('a', 'abc'),
    ('b', 'bcd'),
    ('c', 'cde'),
)

mymultichoices2 = (
    ('会社名1', '会社名1'),
    ('会社名2', '会社名2'),
    ('会社名3', '会社名3'),
)
# yourmultichoice2 = models.CharField(max_length=50,choices=mymultichoices2,blank=True,verbose_name="選択肢４")

class Person(models.Model):
    sw_name = models.CharField(max_length=130,verbose_name="ソフトウェア名称",blank=False, null=True)
    sw_lic_id = models.CharField(max_length=20,verbose_name="ソフトウェアライセンスｉｄ", blank=False, null=True)
    sw_mnt_id = models.CharField(max_length=20,verbose_name="ソフトウェア保守ｉｄ", blank=False, null=True)
    sw_not_use = models.BooleanField(verbose_name=('利用終了'), default=False)
    sw_version = models.CharField(max_length=20,verbose_name="ソフトウェアバージョン番号",blank=True, null=True)
    sw_quantity = models.IntegerField( verbose_name='数量', blank=True, null=True, default=0) 
                #, validators=[validators.minvaluevalidator(0), validators.maxvaluevalidator(100)]) 
                #    , [validators.minvaluevalidator(0.01), validators.maxvaluevalidator(100.00)])
    sw_dev_comp = models.CharField(max_length=50,verbose_name="開発元", blank=True)

    # sw_lic_price= models.decimalfield( verbose_name='購入金額', decimal_places=0, max_digits=1000000000, blank=True, null=True, default=0)
    # sw_mnt_price= models.decimalfield( verbose_name='保守金額', decimal_places=0, max_digits=1000000000, blank=True, null=True, default=0)
    sw_lic_price= models.IntegerField( verbose_name='購入金額', blank=True, null=True, default=0)
    sw_mnt_price= models.IntegerField( verbose_name='保守金額', blank=True, null=True, default=0)

    sw_lic_date = models.DateField(default=timezone.now,verbose_name="購入日付")
    sw_mnt_init_date = models.DateField(default=timezone.now,verbose_name="保守開始日付")
    sw_mnt_update_date = models.DateField(default=timezone.now,verbose_name="保守契約更新日付")
    # sw_sup_date = models.datefield(default=timezone.now,verbose_name="保守期限",blank=True)
    sw_sup_date = models.DateField(verbose_name="保守期限",blank=True, null=True)
    sw_in_charge = models.CharField(max_length=20,verbose_name="担者当名", blank=False, null=True)
    sw_vender_comp = models.CharField(max_length=20,verbose_name="ベンダー名",blank=False, null=True)
    sw_vender_rep = models.CharField(max_length=20,verbose_name="ベンダー担当者名",blank=False, null=True)
    sw_vender_mail = models.EmailField(blank=True,verbose_name="eメール")
    sw_vender_tel = models.CharField(max_length=20,verbose_name="電話番号",blank=False, null=True)
    sw_installed = models.CharField(max_length=100,verbose_name="導入pc", blank=True)
    sw_other = models.CharField(max_length=50,verbose_name="その他", blank=True)

    # version = integerversionfield( )
    # version = autoincversionfield( )

    def save(self, *args, **kwargs):
        # print("=== {} ======================".format(self.ifnochoice)  )
        # if not self.yourmultichoice2:
        #     self.yourmultichoice2 = self.ifnochoice
        super().save(*args, **kwargs)  # call the "real" save() method.
        # do_something_else()
    

app1/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from crispy_forms.bootstrap import InlineField
from django.core.exceptions import ValidationError

# from django.contrib.admin.widgets import AdminDateWidget
# from .utils import OptionalChoiceField



# from people.models import Person
from app1.models import Person


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('sw_name', 'sw_lic_id', 'sw_mnt_id', 'sw_not_use', 'sw_version', 'sw_quantity',
                 'sw_dev_comp', 'sw_lic_price', 'sw_mnt_price', 'sw_lic_date', 'sw_mnt_init_date', 'sw_mnt_update_date', 
                 'sw_sup_date', 'sw_in_charge', 'sw_vender_comp', 'sw_vender_rep', 'sw_vender_mail',
                 'sw_vender_tel','sw_installed','sw_other')
        sw_not_use = forms.BooleanField( label='sw_not_use', required=False, widget=forms.CheckboxInput(attrs={'class': 'check'}))

        # sw_lic_price = forms.DecimalField(label='sw_lic_price', localize=True)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))



# class OutPersonForm(forms.ModelForm):
#     class Meta:
#         model = Person
#         fields = ('name', 'email', 'job_title', 'bio', 'yourchoice1', 'yourchoice2', 'yourmultichoice')
#         yourchoice2 = forms.BooleanField( label='yourchoice2', required=False, widget=forms.CheckboxInput(attrs={'class': 'check'}))
#         yourchoice1 = forms.BooleanField( label='yourchoice1', required=False, widget=forms.CheckboxInput(attrs={'class': 'check'}))

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.helper = FormHelper()
#         self.helper.form_method = 'post'
#         self.helper.add_input(Submit('submit', 'Save person'))
#         self.helper.layout = Layout(
#             InlineField('email', readonly=True),
#         )

app1/views.py
# Create your views here.
from django.shortcuts import render
from django.shortcuts import redirect
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from crispy_forms.bootstrap import InlineField

from django.contrib.auth.models import User

from .filters import UserFilter

from django.http import HttpResponse
from .resources import PersonResource
import tablib
from tablib import Dataset



# Create your views here.
def index(request):
    print("======================================================================")
    return render(request, 'app1:index.html')

def redirect_view(request):
    response = redirect('/app1/')
    return response

###################################################################################    

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render
from django.shortcuts import redirect

# from people.models import Person
# from people.forms import PersonForm
from app1.models import Person
from app1.forms import PersonForm


class PersonListView(ListView):
    model = Person
    context_object_name = 'people'

    def post(self, request):
        post_pks = request.POST.getlist('deletemultiple') 
        # Post.objects.filter(pk__in=post_pks).delete()
        Person.objects.filter(pk__in=post_pks).delete()
        return redirect('app1:person_list')  


class PersonCreateView(CreateView):
    template_name = "app1/person_form.html"
    model = Person
    fields = ('sw_name', 'sw_lic_id', 'sw_mnt_id', 'sw_not_use', 'sw_version', 'sw_quantity',
                'sw_dev_comp', 'sw_lic_price', 'sw_mnt_price', 
                'sw_lic_date', 'sw_mnt_init_date', 'sw_mnt_update_date', 'sw_sup_date', 
                'sw_in_charge', 
                'sw_vender_comp', 'sw_vender_rep', 'sw_vender_mail', 'sw_vender_tel',
                'sw_installed','sw_other')
    success_url = reverse_lazy('app1:person_list')


class PersonUpdateView(UpdateView):
    model = Person
    form_class = PersonForm
    # fields = ('name', 'email', 'job_title', 'bio', 'yourchoice1', 'yourchoice2','yourmultichoice')
    # fields = ('name', 'email', 'job_title', 'bio', )

    template_name = 'app1/person_update_form.html'
    success_url = reverse_lazy('app1:person_list')

    # def get(self, request, *args, **kwargs):
    #     print("===========================>", kwargs['pk'])
    



# class PersonUpdateView(UpdateView):
#     model = Person
#     form_class = PersonForm
#     # fields = ('name', 'email', 'job_title', 'bio', 'yourchoice1', 'yourchoice2','yourmultichoice')
#     # fields = ('name', 'email', 'job_title', 'bio', )

#     template_name = 'app1/person_update_form.html'
#     success_url = reverse_lazy('app1:person_list')

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.helper = FormHelper()
#         self.helper.layout = Layout(
#             'name',
#             InlineField('email', readonly=True),
#         )
        # self.helper.form_method = 'post'
        # self.helper.add_input(Submit('submit', 'Save person'))

class PersonDeleteView(DeleteView):
    model = Person
    # form_class = PersonForm
    success_url = reverse_lazy('app1:person_list')


def search(request):
    user_list = Person.objects.all()
    user_filter = UserFilter(request.GET, queryset=user_list)

    print("==================== ",user_filter)

    # return render(request, 'search/user_list.html', {'filter': user_filter})
    return render(request, 'app1/search_list.html', {'filter': user_filter})


def export(request):
    person_resource = PersonResource()
    dataset = person_resource.export()
    response = HttpResponse(dataset.csv, content_type='text/json')
    response['Content-Disposition'] = 'attachment; filename="persons.csv"'
    return response


# def simple_upload(request):
#     if request.method == 'POST':
#         # person_resource = PersonResource()
#         # dataset = Dataset(headers = ['id','sw_name', 'sw_lic_id', 'sw_mnt_id', 'sw_not_use', 'sw_version', 'sw_quantity',
#         #          'sw_dev_comp', 'sw_lic_price', 'sw_mnt_price', 'sw_lic_date', 'sw_mnt_init_date', 'sw_mnt_update_date', 
#         #          'sw_sup_date', 'sw_in_charge', 'sw_vender_comp', 'sw_vender_rep', 'sw_vender_mail',
#         #          'sw_vender_tel','sw_installed','sw_other', 'version'])
#         # new_persons = request.FILES['myfile']

#         # print("=== simple_upload 1 ===")
#         # imported_data = dataset.load(new_persons.read())
#         # print("=== simple_upload 2 ===")
#         # result = person_resource.import_data(dataset, dry_run=True)  # Test the data import
#         # print("=== simple_upload 3 ===")

#         # if not result.has_errors():
#         #     person_resource.import_data(dataset, dry_run=False)  # Actually import now



#         print("=== simple_upload 1 ===")
#         person_resource = PersonResource()
#         print("=== simple_upload 2 ===")
#         new_persons = request.FILES['myfile']
#         print("=== simple_upload 3 ===")
#             # mydata = tablib.Dataset(headers=[ 'id', 'sw_name', 'sw_lic_id', 'sw_mnt_id', 'sw_not_use', 
#             #                 'sw_version', 'sw_quantity', 'sw_dev_comp', 'sw_lic_price', 'sw_mnt_price', 
#             #                 'sw_lic_date', 'sw_mnt_init_date', 'sw_mnt_update_date', 'sw_sup_date', 
#             #                 'sw_in_charge', 'sw_vender_comp', 'sw_vender_rep', 'sw_vender_mai', 'sw_vender_tel', 
#             #                 'sw_installed', 'sw_other', 'version', ]).load(open(new_persons ).read())
#         # mydata = tablib.Dataset(headers=[ 'id', 'sw_name', 'sw_lic_id', 'sw_mnt_id', 'sw_not_use', 
#         #                 'sw_version', 'sw_quantity', 'sw_dev_comp', 'sw_lic_price', 'sw_mnt_price', 
#         #                 'sw_lic_date', 'sw_mnt_init_date', 'sw_mnt_update_date', 'sw_sup_date', 
#         #                 'sw_in_charge', 'sw_vender_comp', 'sw_vender_rep', 'sw_vender_mai', 'sw_vender_tel', 
#         #                 'sw_installed', 'sw_other', 'version', ]).load(new_persons.read())
#         mydata = tablib.Dataset(headers=[ 'sw_name', 'sw_lic_id', 'sw_mnt_id', 'sw_not_use', 
#                         'sw_version', 'sw_quantity', 'sw_dev_comp', 'sw_lic_price', 'sw_mnt_price', 
#                         'sw_lic_date', 'sw_mnt_init_date', 'sw_mnt_update_date', 'sw_sup_date', 
#                         'sw_in_charge', 'sw_vender_comp', 'sw_vender_rep', 'sw_vender_mai', 'sw_vender_tel', 
#                         'sw_installed', 'sw_other' ]).load(new_persons.read())
#         print("=== simple_upload 4 ===")
#         result = person_resource.import_data(mydata, dry_run=True)
#         if not result.has_errors():
#             result = person_resource.import_data(mydata, dry_run=False)


#     return render(request, 'app1/simple_upload.html')

def simple_upload(request):
    if request.method == 'POST':
        person_resource = PersonResource()
        dataset = Dataset()
        new_persons = request.FILES['myfile']

        imported_data = dataset.load(new_persons.read())
        result = person_resource.import_data(dataset, dry_run=True)  # Test the data import

        if not result.has_errors():
            person_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'app1/simple_upload.html')

templates/app1/person_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
    <table class="table table-bordered">
        <thead>
        <tr>
            {% comment %} <th>Name</th>
            <th>Email</th>
            <th>Job Title</th> {% endcomment %}
            <th>名前(編集)</th>
            <th>eメール</th>
            <th>職業</th>
        </tr>
        </thead>
        <tbody>
            <tr>
            <td>{{ person.name }}</td>
            <td>{{ person.email }}</td>
            <td>{{ person.job_title }}</td>
            </tr>
        </tbody>
    </table>

        <input type="submit" value="Confirm">
    </form>
{% endblock %}

templates/app1/person_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load l10n %}

<!-- Page Content -->
<div id="page-content-wrapper">

  {% block content %}
    <form method="post" novalidate>
      {% csrf_token %}
      <div class="row mt-2">
        <div class="col-6">
          {{ form.sw_name|as_crispy_field }}
        </div>
        <div class="col-3">
          {{ form.sw_lic_id|as_crispy_field }}
        </div> 
        <div class="col-3">
          {{ form.sw_mnt_id|as_crispy_field }}
        </div> 
      </div>
      
      <div class="row mt-2">
        <div class="col-3">
          {{ form.sw_version|as_crispy_field }}
        </div>
        <div class="col-3">
          {{ form.sw_quantity|as_crispy_field }}
        </div> 
        <div class="col-3">
          {{ form.sw_lic_price|as_crispy_field }}
          {% comment %} {{ form.sw_lic_price|intcomma }} {% endcomment %}
        </div> 
        <div class="col-3">
          {{ form.sw_mnt_price|as_crispy_field }}
        </div> 
      </div>

      <div class="row mt-2">
        <div class="col-3">
          {{ form.sw_lic_date|as_crispy_field }}
        </div>
        <div class="col-3">
          {{ form.sw_mnt_init_date|as_crispy_field }}
        </div> 
        <div class="col-3">
          {{ form.sw_mnt_update_date|as_crispy_field }}
        </div> 
        <div class="col-3">
          {{ form.sw_sup_date|as_crispy_field }}
        </div> 

      <div class="row mt-2">
        <div class="col-3">
          {{ form.sw_in_charge|as_crispy_field }}
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-3">
          {{ form.sw_vender_comp|as_crispy_field }}
        </div> 
        <div class="col-3">
          {{ form.sw_vender_rep|as_crispy_field }}
        </div> 
        <div class="col-3">
          {{ form.sw_vender_mail|as_crispy_field }}
        </div> 
        <div class="col-3">
          {{ form.sw_vender_tel|as_crispy_field }}
        </div> 
      </div>



      

      <div class="row mt-2">
        <div class="col-6">
          {% comment %} {{ form.name2|as_crispy_field }} {% endcomment %}
          {% comment %} <input type="text" name="name2" id="name2" /> {% endcomment %}

          <label for="name">開発元</label>

        </div>

      <div class="row mt-2">
      {% comment %} <div class="row mt-2" style="height:50px" > {% endcomment %}
        <div class="col-6">
         {% comment %} <div class="col-md-6 col-lg-6 B h-100">   {% endcomment %}
          <input list="browsers" id="person_browser" name="person_browser" placeholder="一覧からベンダーを選択して下さい" />
          <datalist id="browsers">
            <option value="日本ＩＢＭ">
            <option value="マイクロソフト">
            <option value="Internet Explorer">
            <option value="Opera">
            <option value="Safari">
            <option value="Microsoft Edge">
          </datalist>
        </div>
      </div>
      
      <div class="row mt-2">
        <div class="col-6">
          {{ form.sw_installed|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.sw_other|as_crispy_field }}
        </div>
      </div>

      <div class="row mt-2">
          {{ form.sw_not_use|as_crispy_field }}
      </div>

      <div class="row mt-2">
        <div class="col-3">
          <button type="submit" class="btn btn-success">保存</button>
        </div>
      </div>
      {% comment %} <button type="submit" class="btn btn-success">保存</button> {% endcomment %}

    </form>
  {% endblock %}

</div>

templates/app1/person_form_boot.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

<!-- Page Content -->
<div id="page-content-wrapper">

  {% block content %}
    <form method="post" novalidate>
      {% csrf_token %}
      <div class="row">
        <div class="col-6">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.email|as_crispy_field }}
        </div>
      </div>
      {{ form.job_title|as_crispy_field }}
      {{ form.bio|as_crispy_field }}<br>
      <div class="row">
        <div class="col-3">
          {{ form.yourchoice1|as_crispy_field }}
        </div>
        <div class="col-3">
          {{ form.yourchoice2|as_crispy_field }}
        </div>
        <div class="col-3">
          {{ form.person_initial_date|as_crispy_field }}
        </div>
        <div class="col-3">
          {{ form.person_update_date|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          {{ form.yourmultichoice|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          {% comment %} {{ form.name2|as_crispy_field }} {% endcomment %}
          {% comment %} <input type="text" name="name2" id="name2" /> {% endcomment %}

          <label for="name">ブラウザー選択</label>
          <input list="browsers" id="name2" name="name2" placeholder="一覧からブラウザーを選択して下さい" />
          <datalist id="browsers">
            <option value="Chrome">
            <option value="Firefox">
            <option value="Internet Explorer">
            <option value="Opera">
            <option value="Safari">
            <option value="Microsoft Edge">
          </datalist>

        </div>
      </div>
      <button type="submit" class="btn btn-success">保存</button>
      {% comment %} <button type="submit" class="btn btn-success">Save person</button> {% endcomment %}
    </form>
  {% endblock %}

</div>

templates/app1/person_list.html
{% extends 'base.html' %}

{% block content %}
  <p>
    <a href="{% url 'app1:person_add' %}" class="btn btn-primary">追加</a>
  </p>

  {% comment %} <form action="{% url 'delete' person.pk %}" method="post">  {% endcomment %}
  {% comment %} <form action="{% url 'polls:vote' question.id %}" method="post"> {% endcomment %}

  <form action="" method="POST">
  {% comment %} <form action="{% url 'deletesomeall' person.pk %}" method="POST"> {% endcomment %}
  {% comment %} <form action="deletesomeall/person.pk" method="POST"> {% endcomment %}

  {% comment %} <form action="" method="GET">{% csrf_token %} {% endcomment %}
  {% comment %} <form action="{% url 'deletesomeall' person.pk  %}"  method="POST">{% csrf_token %} {% endcomment %}
  {% comment %} <form action="{% url 'deletesomeall' method="GET" %}" >  {% endcomment %}
  {% comment %} <button typeAdd a person="submit">削除</button> {% endcomment %}

    {% csrf_token %}
    <table class="table table-bordered">
      <thead>
        <tr>
          {% comment %} <th>Name</th>
          <th>Email</th>
          <th>Job Title</th> {% endcomment %}
          <th>ソフトウェア名称</th>
          <th>保守金額</th>
          <th>保守契約更新日付</th>
          <th>削除</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        {% for person in people %}
          <tr>
            {% comment %} <td><input type="checkbox" name="delete_person" value="{{ person.pk }}"></td> {% endcomment %}
            <td><a href="{% url 'app1:person_edit' person.pk %}">{{ person.sw_name }}</a></td>
            {% comment %} <td>{{ person.name }}</td> {% endcomment %}
            <td>{{ person.sw_mnt_price }}</td>
            <td>{{ person.sw_mnt_update_date }}</td>
            {% comment %} <th>削除</th> {% endcomment %}
            <th><a href="{% url 'app1:delete' person.pk %}">削除</a></th>
            <td><input type="checkbox" name="deletemultiple" value="{{ person.pk }}"></td>
          </tr>
        {% empty %}
          <tr class="table-active">
            <td colspan="3">No data</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <button type="submit">削除</button>
  </form>
  {% comment %} <p>
    <a href="{% url 'person_edit' pk=3 %}" class="btn btn-primary">Add a person</a>
  </p> {% endcomment %}
  <p>
    <a href="{% url 'app1:person_add' %}" class="btn btn-primary">追加</a>
  </p>
{% endblock %}

templates/app1/search_list.html
{% extends 'base.html' %}

{% comment %}
{% block content %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>

  <div class="row mt-3">
    <h5>該当レコード</h5>
  </div>



  {% for person in filter.qs %}
    <li> <td><a href="{% url 'app1:person_edit' person.pk %}">{{ person.sw_name }} - {{person.sw_mnt_update_date}} - {{ person.sw_mnt_price }} </a></td> </li>
  {% endfor %}
  </ul>
{% endblock %}
{% endcomment %}

{% load widget_tweaks %}

<div id="page-content-wrapper">

  {% block content %}
    <form method="get">
      {% csrf_token %}
        <h4 style="margin-top: 0">Filters</h4>
        
        {% comment %}
        <div>
          <form>
            {{ filter.form.as_p }}
          </form>
        </dvi>
        {% endcomment %}
        

        <div class="row mt-2">
          <div class="col-2">
            <label>ソフトウェア名称:</label>
          </div>
          <div class="col-3">
            {{ filter.form.sw_name__contains }}
          </div>
        </dvi>

        <div class="row mt-2">
          <div class="col-2">
            <label>保守契約更新日:</label>
          </div>
          <div class="col-3">
            {{ filter.form.sw_mnt_update_date__range }}
          </div>
        </dvi>

        <div class="row mt-2">
          <div class="col-12">
            <label>検索例:2021-01-01,2021-12-01</label>
          </div>
        </dvi>

        
        {% comment %}
        <div class="row"> 
          <div class="form-group col-sm-4 col-md-3">
            {{ filter.form.sw_name.label_tag }}
            {{ "-----" }}
            <h5>h5h5h5</h5>
            {% render_field filter.form.sw_name class="form-control" %}
          </div>
        </div>
        {% endcomment %}
        
      <div class="row mt-2">
        <div class="col-3">
          <button type="submit"P class="btn btn-primary">
            <span class="glyphicon glyphicon-search"></span> Search
          </button>
        </div>
      </div>
    </form>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ソフトウェア名称</th>
          <th>保守契約更新日</th>
          <th>保守金額</th>
        </tr>
      </thead>
      <tbody>
        {% for user in filter.qs %}
          <tr>
            {% comment %} <td>{{ user.sw_name }}</td> {% endcomment %}
            <td><a href="{% url 'app1:person_edit' user.pk %}">{{ user.sw_name }}</a></td>
            <td>{{ user.sw_mnt_update_date }}</td>
            <td>{{ user.sw_mnt_price }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="5">No data</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endblock %}
</div>jj

templates/app1/simple_upload.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}