app1/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from app1.views import PersonListView, PersonCreateView, PersonUpdateView, PersonDeleteView
from django.conf.urls import url

# from django_filters.views import FilterView
from .models import Person

app_name ="app1"

urlpatterns = [
    path('person_add/', PersonCreateView.as_view(), name='person_add'),
    path('', PersonListView.as_view(), name='person_list'),
    path('person_list/', PersonListView.as_view(), name='person_list'),
    path('<int:pk>/edit/', PersonUpdateView.as_view(), name='person_edit'),
    path('<int:pk>/delete/', PersonDeleteView.as_view(), name='delete'),
    # path('search/', views.search, name='search'),
    # url(r'^search/$', FilterView.as_view(model=Person)),
    url(r'^search/$', views.search, name='search_list' ),
    url(r'^export/$', views.export, name='export'),
    url(r'^simple_upload/$', views.simple_upload, name='simple_upload'),


]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView 

from . import views as myviews
from django.contrib.auth import views


urlpatterns = [
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls),
    path('mysite_2/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path("register/", myviews.register, name="register"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]

templates/base.html
<!doctype html>"
{% load crispy_forms_tags %}
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			{% comment %} background-color:#111; {% endcomment %}
			background-color:green;
			overflow-x: :hidden;
			padding-top:20px;
		}
 
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:25px;
			{% comment %} color: #818181; {% endcomment %}
			color: #000000;
			display:block;
		}
 
		mysite.sidenav a:hover{
			color:#f1f1f1;
		}	
 
		.main{
			margin-left:160px;
			padding: 0px 10px;
		}
 
	</style>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	
	{% comment %} <title>{% block title %}Tim's Site{% endblock %}</title> {% endcomment %}
</head>

{% comment %} <header class="justify-content-end d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm"> {% endcomment %}
<header class="justify-content-end d-flex flex-column flex-md-row align-items-center p-1 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  {% comment %} <p class="h5 my-0 me-md-auto fw-normal">Company name</p> {% endcomment %}
  {% comment %} <nav class="my-2 my-md-0 me-md-3"> {% endcomment %}
    <nav class="my-2 my-md-0 me-md-3">
        {% comment %} <a class="p-2 text-dark" href="#">Features</a>
        <a class="p-2 text-dark" href="#">Enterprise</a>
        <a class="p-2 text-dark" href="#">Support</a>
        <a class="p-2 text-dark" href="#">Pricing</a> {% endcomment %}

		{% comment %} <li class="nav-item dropdown"> {% endcomment %}
		<a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Export/Import</a>
		<ul class="dropdown-menu" aria-labelledby="dropdown01">
			{% comment %} <li><a class="dropdown-item" href="#">Export</a></li> {% endcomment %}
			<li><a class="dropdown-item" href="{% url 'app1:export' %}">Export</a></li>
			{% comment %} <li><a class="dropdown-item" href="#">Import</a></li> {% endcomment %}
			<li><a class="dropdown-item" href="{% url 'app1:simple_upload' %}">Import</a></li>
		</ul>
        {% comment %} </li> {% endcomment %}




    </nav>
  {% comment %} <a class="btn btn-outline-primary" href="#">Sign up</a> {% endcomment %}
</header>
 
<body>
	<div class="sidenav">
		<a href="/">ホーム</a>
		{% comment %} <a href="/create">Create</a> {% endcomment %}
		{% comment %} <a href="/2">View</a> {% endcomment %}
		<a href="{% url 'app1:person_add' %}">新規</a>
		<a href="{% url 'app1:person_list' %}">リスト</a>
		<a href="{% url 'app1:search_list' %}">サーチ</a>
		<a href="{% url 'logout' %}">
            <p class="fw-lighter">Logoff</p>
        </a>
	</div>

	<div id="content", name="content", class="main">
		<div class="row justify-content-left">
			<div class="col-8">
				<h1 class="mt-2">ライセンス管理(mysite_3)</h1>
				<hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}

			</vid>
		</div>
	</div>

	 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


</body>
</html>

templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}ホーム{% endblock %}

{% block content %}
{% csrf_token %}
{{ form|crispy }}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
    <p>You are not logged in</p>
    <div class="list-group">
        <a href="{% url 'login' %}">Log In</a>
        <a href="{% url 'register' %}">Register</a>
    </div>  
{% endif %}
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
	<button type="submit" class="btn btn-success">Register</button>
    {% comment %} {% if form.errors %}
        {{ form.non_field_errors }}
    {% endif %} {% endcomment %}
    <p class="text-muted fst-italic" >登録後ログインしてください</p>
    {% comment %} <small class="text-muted">登録後ログインしてください</small> {% endcomment %}
    </form>
{% endblock %}